services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      WATCHPACK_POLLING: "true"
      PORT: 3001
      INTERNAL_API_URL: http://backend:3000
      NEXT_PUBLIC_API_URL: http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next    
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: package.json
    depends_on: [backend]
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment: 
      DATABASE_URL: postgresql://postgres:Akudavid123@postgre:5432/risetproject
      CLICKHOUSE_URL: http://default:root@clickhouse:8123/analytics
      PORT: 3000
      DEBUG : true
    depends_on: 
      postgre : 
        condition: service_healthy
    volumes:
    - ./backend:/usr/src/app
    - /usr/src/app/node_modules
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /usr/src/app/src
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ./backend/package.json

  users-service:
    build:
      context: ./microservices
      dockerfile: apps/users/Dockerfile
    ports:
      - "3004:3004"
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: Akudavid123
      DATABASE_NAME: usersDatabase
      DATABASE_URL: mysql://root:Akudavid123@mysql:3306/usersDatabase
      PORT: 3004
      DEBUG: "true"
    depends_on: 
      mysql : 
        condition: service_healthy
    volumes:
    - ./microservices/apps/users:/usr/src/app/apps/users
    - /usr/src/app/apps/users/node_modules
    develop:
      watch:  
        - action: sync
          path: ./microservices/apps/users/src
          target: /usr/src/app/apps/users/src
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ./microservices/apps/users/package.json

  api-gateway:
    build:
      context: ./microservices
      dockerfile: apps/api/Dockerfile
    ports:
      - "3006:3006"
    environment:
      TCP_USERSSERVICE_HOST: users-service
      TCP_USERSSERVICE_PORT: 3004
      TCP_CONTENTSSERVICE_HOST: contents-service
      TCP_CONTENTSSERVICE_PORT: 3005
      TCP_QUERIESSERVICE_HOST: queries-service
      TCP_QUERIESSERVICE_PORT: 3007
      PORT: 3006
      DEBUG: "true"
    depends_on: 
      mysql : 
        condition: service_healthy
    volumes:
    - ./microservices/apps/api:/usr/src/app/apps/api
    - /usr/src/app/apps/api/node_modules
    develop:
      watch:  
        - action: sync
          path: ./microservices/apps/api/src
          target: /usr/src/app/apps/api/src
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ./microservices/apps/api/package.json

  queries-service:
    build:
      context: ./microservices
      dockerfile: apps/queries/Dockerfile
    ports:
      - "3007:3007"
    environment:
      CLICKHOUSE_URL: http://default:root@clickhouse:8123/analytics
      PORT: 3007
      DEBUG: "true"
    depends_on: 
      postgre : 
        condition: service_healthy
    volumes:
    - ./microservices/apps/queries:/usr/src/app/apps/queries
    - /usr/src/app/apps/queries/node_modules
    develop:
      watch:
        - action: sync
          path: ./microservices/apps/queries/src
          target: /usr/src/app/apps/queries/src
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ./microservices/apps/queries/package.json

  contents-service:
    build:
      context: ./microservices
      dockerfile: apps/contents/Dockerfile
    ports:
      - "3005:3005"
    environment:
      DATABASE_URL: postgresql://postgres:Akudavid123@postgre:5432/risetproject
      PORT: 3005
      DEBUG: "true"
    depends_on: 
      postgre : 
        condition: service_healthy
    volumes:
    - ./microservices/apps/contents:/usr/src/app/apps/contents
    - /usr/src/app/apps/contents/node_modules
    develop:
      watch:
        - action: sync
          path: ./microservices/apps/contents/src
          target: /usr/src/app/apps/contents/src
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ./microservices/apps/contents/package.json

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Akudavid123
      MYSQL_DATABASE: usersDatabase
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pAkudavid123"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-conf/gtid.cnf:/etc/mysql/conf.d/gtid.cnf

  postgre:
    image: postgres
    command: ["postgres", "-c", "wal_level=logical"]
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: risetproject
      POSTGRES_PASSWORD: Akudavid123
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  kafka: 
    image: quay.io/debezium/kafka:3.6
    hostname: kafka
    ports: 
      - 9092:9092
    environment:
      CLUSTER_ID: 1
      NODE_ID: 1
      NODE_ROLE: combined
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS : PLAINTEXT://kafka:9092
  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    depends_on:
      kafka : 
        condition : service_started
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"

  clickhouse:
    image: clickhouse/clickhouse-server
    ports: 
     - 8123:8123
     - 9000:9000
    environment:
      CLICKHOUSE_PASSWORD: root
    ulimits:
      nofile:
        soft: 262144
        hard: 262144 
    volumes:
      - ./clickhouse/config/my-config-setup.xml:/etc/clickhouse-server/config.d/my-config-setup.xml
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init-db.sql
  connect:
    image: quay.io/debezium/connect:3.6
    ports: 
      - 8083:8083
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      BOOTSTRAP_SERVERS: kafka:9092
    depends_on: 
      kafka:
        condition: service_started
      postgre:
        condition: service_healthy
  
volumes:
  postgres_data:
  clickhouse_data:
  mysql_data: