services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      WATCHPACK_POLLING: "true"
      PORT: 3001
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: package.json
    depends_on: [backend]
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment: 
      DATABASE_URL: postgresql://postgres:Akudavid123@postgre:5432/risetproject
      PORT: 3000
      DEBUG : true
    depends_on: [postgre]
    volumes:
    - ./backend:/usr/src/app
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /usr/src/app/src
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ./backend/package.json

  postgre:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: risetproject
      POSTGRES_PASSWORD: Akudavid123
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/

  
  kafka: 
    image: quay.io/debezium/kafka:3.6
    hostname: kafka
    ports: 
      - 9092:9092
    environment:
      CLUSTER_ID: 1
      NODE_ID: 1
      NODE_ROLE: combined
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS : PLAINTEXT://kafka:9092
  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"

  connect:
    image: quay.io/debezium/connect:3.6
    ports: 
      - 8083:8083
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      BOOTSTRAP_SERVERS: kafka:9092
    depends_on: [kafka]

   
  
volumes:
  postgres_data: