services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: node:24-slim
    ports:
      - "3001:3001"
    environment:
      - WATCHPACK_POLLING=true
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: package.json
    depends_on:
      - backend
      
  backend:
    image: node:24-slim
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on: [postgre]

  postgre:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: risetproject
      POSTGRES_PASSWORD: Akudavid123
    ports:
      - 5432:5432
  kafka: 
    image: quay.io/debezium/kafka:3.6
    hostname: kafka
    ports: 
      - 9092:9092
    environment:
      CLUSTER_ID: 1
      NODE_ID: 1
      NODE_ROLE: combined
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS : PLAINTEXT://kafka:9092
  
  connect:
    image: quay.io/debezium/connect:3.6
    ports: 
      - 8083:8083
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
    depends_on: [kafka]
      
